// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ileywkgxavikqrjtpurt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsZXl3a2d4YXZpa3FyanRwdXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMTY1NTgsImV4cCI6MjA3OTg5MjU1OH0.hN_LzPvLxULslHevJsJN_wvJqD0xPzsAFNBj-Wlz6cY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});