// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upeekandiuhoyghextyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZWVrYW5kaXVob3lnaGV4dHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjIzMDAsImV4cCI6MjA2ODY5ODMwMH0.OR-BWUQVxwUDfWVTbMOZcaEBiIN7CzL1nmMWOnf9keI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});